// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/reductor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение, описывающее длинный URL и пользователя
type LinkUsrReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"` // числа здесь - порядок полей в сообщении
	Usr           string                 `protobuf:"bytes,2,opt,name=usr,proto3" json:"usr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUsrReq) Reset() {
	*x = LinkUsrReq{}
	mi := &file_proto_reductor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUsrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUsrReq) ProtoMessage() {}

func (x *LinkUsrReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reductor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUsrReq.ProtoReflect.Descriptor instead.
func (*LinkUsrReq) Descriptor() ([]byte, []int) {
	return file_proto_reductor_proto_rawDescGZIP(), []int{0}
}

func (x *LinkUsrReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *LinkUsrReq) GetUsr() string {
	if x != nil {
		return x.Usr
	}
	return ""
}

// Ответное сообщение короткий URL и ошибка
type StrErrResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrErrResp) Reset() {
	*x = StrErrResp{}
	mi := &file_proto_reductor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrErrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrErrResp) ProtoMessage() {}

func (x *StrErrResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reductor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrErrResp.ProtoReflect.Descriptor instead.
func (*StrErrResp) Descriptor() ([]byte, []int) {
	return file_proto_reductor_proto_rawDescGZIP(), []int{1}
}

func (x *StrErrResp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *StrErrResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proto_reductor_proto protoreflect.FileDescriptor

const file_proto_reductor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/reductor.proto\x12\breductor\"2\n" +
	"\n" +
	"LinkUsrReq\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x10\n" +
	"\x03usr\x18\x02 \x01(\tR\x03usr\";\n" +
	"\n" +
	"StrErrResp\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2H\n" +
	"\x0fReductorService\x125\n" +
	"\aAddLink\x12\x14.reductor.LinkUsrReq\x1a\x14.reductor.StrErrRespB7Z5github.com/developerc/reductorUrl/internal/grpc/protob\x06proto3"

var (
	file_proto_reductor_proto_rawDescOnce sync.Once
	file_proto_reductor_proto_rawDescData []byte
)

func file_proto_reductor_proto_rawDescGZIP() []byte {
	file_proto_reductor_proto_rawDescOnce.Do(func() {
		file_proto_reductor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reductor_proto_rawDesc), len(file_proto_reductor_proto_rawDesc)))
	})
	return file_proto_reductor_proto_rawDescData
}

var file_proto_reductor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_reductor_proto_goTypes = []any{
	(*LinkUsrReq)(nil), // 0: reductor.LinkUsrReq
	(*StrErrResp)(nil), // 1: reductor.StrErrResp
}
var file_proto_reductor_proto_depIdxs = []int32{
	0, // 0: reductor.ReductorService.AddLink:input_type -> reductor.LinkUsrReq
	1, // 1: reductor.ReductorService.AddLink:output_type -> reductor.StrErrResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reductor_proto_init() }
func file_proto_reductor_proto_init() {
	if File_proto_reductor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reductor_proto_rawDesc), len(file_proto_reductor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reductor_proto_goTypes,
		DependencyIndexes: file_proto_reductor_proto_depIdxs,
		MessageInfos:      file_proto_reductor_proto_msgTypes,
	}.Build()
	File_proto_reductor_proto = out.File
	file_proto_reductor_proto_goTypes = nil
	file_proto_reductor_proto_depIdxs = nil
}
