// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/reductor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReductorService_AddLink_FullMethodName = "/reductor.ReductorService/AddLink"
)

// ReductorServiceClient is the client API for ReductorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Определение сервиса
type ReductorServiceClient interface {
	AddLink(ctx context.Context, in *LinkUsrReq, opts ...grpc.CallOption) (*StrErrResp, error)
}

type reductorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReductorServiceClient(cc grpc.ClientConnInterface) ReductorServiceClient {
	return &reductorServiceClient{cc}
}

func (c *reductorServiceClient) AddLink(ctx context.Context, in *LinkUsrReq, opts ...grpc.CallOption) (*StrErrResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrErrResp)
	err := c.cc.Invoke(ctx, ReductorService_AddLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReductorServiceServer is the server API for ReductorService service.
// All implementations must embed UnimplementedReductorServiceServer
// for forward compatibility.
//
// Определение сервиса
type ReductorServiceServer interface {
	AddLink(context.Context, *LinkUsrReq) (*StrErrResp, error)
	mustEmbedUnimplementedReductorServiceServer()
}

// UnimplementedReductorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReductorServiceServer struct{}

func (UnimplementedReductorServiceServer) AddLink(context.Context, *LinkUsrReq) (*StrErrResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedReductorServiceServer) mustEmbedUnimplementedReductorServiceServer() {}
func (UnimplementedReductorServiceServer) testEmbeddedByValue()                         {}

// UnsafeReductorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReductorServiceServer will
// result in compilation errors.
type UnsafeReductorServiceServer interface {
	mustEmbedUnimplementedReductorServiceServer()
}

func RegisterReductorServiceServer(s grpc.ServiceRegistrar, srv ReductorServiceServer) {
	// If the following call pancis, it indicates UnimplementedReductorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReductorService_ServiceDesc, srv)
}

func _ReductorService_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkUsrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReductorServiceServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReductorService_AddLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReductorServiceServer).AddLink(ctx, req.(*LinkUsrReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReductorService_ServiceDesc is the grpc.ServiceDesc for ReductorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReductorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reductor.ReductorService",
	HandlerType: (*ReductorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLink",
			Handler:    _ReductorService_AddLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reductor.proto",
}
